name: misc
description: |-
  [misc]
  A dependncy less dart package.
version: 2025.501.111
homepage: 
repository: https://github.com/dart-pkg/misc
environment:
  sdk: ^3.7.2
dev_dependencies:
  lints: ^5.1.1
  output: ^2025.430.1731
  test: ^1.25.15
dependencies:
  path: ^1.9.1
