name: "misc"
description: |-
  [misc]
  A dependncy less dart package.
version: 2025.426.359
homepage: null
repository: "https://github.com/dart-pkg/misc"
environment:
  sdk: "^3.7.2"
dev_dependencies:
  lints: ^5.1.1
  output: ^1.0.7
  test: ^1.25.15
