name: "misc"
description: "misc project"
version: "2025.422.1753"
homepage: null
repository: "https://github.com/dart-pkg/misc"
environment:
  sdk: "^3.7.2"
dependencies: null
dev_dependencies:
  lints: ^5.1.1
  output: ^1.0.6
  test: ^1.25.15
